### PR TITLE
Resolve first exercise inline-block

### PR DESCRIPTION
**Pull request by lambrugeorge**
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by lambrugeorge** [comment]
finish 01-margin-and-padding-1 The odin project.

**Comment by lambrugeorge** [comment]
finish exercise 02-margin-and-padding-2

**Comment by lambrugeorge** [comment]
02-margin-and-padding-2

**Comment by rlmoser99** [comment]
Closing this PR because we do not merge in solutions into this exercise repo.

**Pull request closed without merging**
