### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by midnightmoet**
Just corrected a spelling error (complement -> compliment)

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by midnightmoet** [comment]
spelling error in main README file corrected

**Comment by midnightmoet** [comment]
That change in verbiage would be ideal if you are able to make the adjustment / change.  Thanks.

**Comment by thatblindgeye** [comment]
@midnightmoet Would you want to push that change to your PR?

**Comment by midnightmoet** [comment]
Yes

**Pull request closed without merging**
