### PR TITLE
Flex and Foundations: add alt text for accessibility (#201)

### LINKED ISSUE #201: Flex and Foundations: add alt text for accessibility.
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Four html files were missing the alt attribute in the img tag. This compromises accessibility. In addition, the use of alternative texts is considered a good practice and should be encouraged whenever appropriate.

**2. Acceptance Criteria:**

- [x] Add alternative texts where missing

### PR DESCRIPTION
**Pull request by Amandasilvbr**
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [] I have ensured that the TOP solution files match the Desired Outcome image

<hr>

**1. Because:**

-Four html files were missing the alt attribute in the img tag. This compromises accessibility. In addition, the use of alternative texts is considered a good practice and should be encouraged whenever appropriate.
Closes #201

**2. This PR:**
 
-Four images were missing the "alt" attribute, so I added the alt texts to each of them.

If anyone has any suggestions, let's talk!

### CODE REVIEW

**Review by dm-murphy — APPROVED** [review]
Thanks @Amandasilvbr! 

Great work and initiative in finding these and making the PR. Appreciate the help! 🙂

**Comment by Amandasilvbr** [comment]
You are welcome!

**Comment by YoRobotCop** [comment]
Gracias por el soporte

**Comment by YoRobotCop** [comment]
Domain onion.onion

**Pull request merged**
