### PR TITLE
CSS Grid Exercise 03-grid-layout-3: Amend README

### PR DESCRIPTION
**Pull request by jernestmyers**
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this PR follows the `where the change occurs: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

- [x] If updates were made to any solution code, I have ensured that the Desired Outcome image is accurate
- [x] If one exists, I have linked a related open issue to this PR in Step 2 below
- [x] If changes were requested, I have made them and re-requested a review from the maintainer (top of the right sidebar)

**1. Description of the Changes**
 
The Self Check in the README for this exercise said to nest a grid container into the `header` grid container, like so:
```md
- The header element has two columns
- The header element contains another grid that has two columns
```

The solution on the other hand creates four columns, like so:
```css
.menu ul {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
}
```

I don't particularly think the `.menu ul` container necessitates grid, but I also understand how doing so may help reinforce the concept. For this reason, I chose only to update the Self Check to reflect the solution.

**2. Related Issue**

Closes #XXXXX

### CODE REVIEW

**Review by dm-murphy — CHANGES_REQUESTED** [review]
Thanks for bringing this one up! This was intended to be "four" columns instead of "two" but looking over it again now I think the entire bullet is causing extra confusion. There was another learner on the Discord who was confused by the wording of "contains" in this context for this bullet.

It might be best to remove this line entirely. The previous bullet already explains the two columns in the header. And the following bullet explains that the `menu ul` selector has another grid. So this line really isn't serving any purpose.

The other option is removing this line while also including the bit about "four columns" in the next bullet. That way it is clear that the `menu ul` selector contains another grid with four columns.

Let me know your thoughts or if you wanted to make another suggestion.

As for your note about the use of a grid for the menu, yes the exercise is intending for learners to rely only on CSS Grid to get this done instead of using Flexbox as mentioned in the introduction of the exercise.

**Comment by jernestmyers** [comment]
Ah, I didn't even notice that! Apologies, I haven't done these exercises.

After looking over the boilerplate HTML and the Self Check points, I'm inclined to agree that it should just be removed. I'm not sure it's necessary to add the note about four columns for the `menu ul`. It feels intuitive enough given its contents.

**Comment by dm-murphy** [comment]
> Ah, I didn't even notice that! Apologies, I haven't done these exercises.
> 
> After looking over the boilerplate HTML and the Self Check points, I'm inclined to agree that it should just be removed. I'm not sure it's necessary to add the note about four columns for the `menu ul`. It feels intuitive enough given its contents.

No worries @jernestmyers! You can push a new commit to remove the whole line and then request a re-review in the top right of the sidebar. Thanks!

**Review by dm-murphy — APPROVED** [review]
Thanks for the contribution! We'll see if this helps clarify some of the confusion.

**Pull request merged**
