### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Na-mi20**
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by Na-mi20** [comment]
Nothing

**Comment by Na-mi20** [comment]
/*changes*/

**Comment by lordparvis** [comment]
> /_changes_/

what is this?

**Comment by MaoShizhong** [comment]
As per the [repo README](https://github.com/TheOdinProject/css-exercises), please don't open PRs for your own solutions.

**Pull request closed without merging**
