### PR TITLE
Add loading attribute for img

### PR DESCRIPTION
**Pull request by BiswajitHemram**
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by BiswajitHemram** [comment]
#328 Add loading attribute for img which help us to load image

**Comment by LeoKirasic** [comment]
Hey, @BiswajitHemram Thank you for creating this PR.

I'm not entirely sure that this change would be beneficial as the extra tags could confuse the learners this early on.

As you left the "Because" section of the PR empty, could you please elaborate on this change?

Thank you!

**Comment by thatblindgeye** [comment]
For the context of these exercises, this attribute isn't really necessary. The "eager" value is also the default value of the attribute. @BiswajitHemram can you provide any more context behind this update?

**Comment by thatblindgeye** [comment]
Due to inactivity and the above comments will be closing this for now

**Pull request closed without merging**
