### PR TITLE
flex/07-flex-layout-2 : fix solution.css inconsistency

### PR DESCRIPTION
**Pull request by dotarjun**
## Because 

The instructions indicate the sidebar div to be 300px whereas it was found that it's 332px in ``solution.css``

## This PR

- Changes the ``box-sizing`` property of the .sidebar to ``border-box``

## Issue

Closes https://github.com/TheOdinProject/css-exercises/issues/269

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by xandora** [comment]
@dotarjun You seem to have completely reformatted every line in this file, making it impossible to review your actual change. Can you revert the formatting back to what it was and resubmit without running whatever formatter you have installed?

**Comment by dotarjun** [comment]
@xandora I have tried to fix the formatting. Do check the changes.

**Review by xandora — CHANGES_REQUESTED** [review]
We actually had a discussion about this internally, and it was put forth that nobody has been introduced to `border-box` by this point in the curriculum. As such, it doesn't make sense for it to be part of the solution.

This is the right solution to the problem though, but it feels like it's in the wrong place. Can you make an additional change to this that:

* Moves this `box-sizing: border-box` to the non-solution part of the code,
* Add it to the exercise code in the non-solution section, and
* Check that the above changes don't change the exercise significantly.

I know this is changing the goalposts slightly, but it should make the exercise better overall for learners.

**Comment by dotarjun** [comment]
@xandora 

- [x] Moves this box-sizing: border-box to the non-solution part of the code.
- [x] Add it to the exercise code in the non-solution section.
- [x] Check that the above changes don't change the exercise significantly.

I have done all that. Should I add a comment next to the ``border-box`` property so the learners don't feel confused and anxious about this new property that's suddenly being used which they haven't learned about yet?

**Review by dotarjun — COMMENTED** [review]
Adds ``box-sizing`` to non solution part so the learners arent bothered by it

**Comment by dotarjun** [comment]
Can this be reviewed for changes

**Review by xandora — APPROVED** [review]
looks good.

**Pull request merged**
