### PR TITLE
Update solution.html

### PR DESCRIPTION
**Pull request by abdelhakim54**
the odd elements do not necessarly have to share a common class in this example , because they are already p elements .

you may need to see the css file to get the idea

### CODE REVIEW

**Comment by thatblindgeye** [comment]
@abdelhakim54 the point of this exercise is to practice class and ID selectors. Removing the classes just because all the odd elements are already `p` elements defeats the purpose of the exercise.

**Comment by abdelhakim54** [comment]
you're right , the purpose is to get familiar with selectors , howrever it's still a valid answer . Maybe making them all with the same tag ( <p> or <div> ) will serve better the desired purpose .

**Comment by thatblindgeye** [comment]
For this specific exercise the desired purpose is class and ID selectors, not type /element selectors like `p`.  So while using the `p` selector is a valid answer in general, it does not fit with the desired purpose of this exercise.

**Comment by abdelhakim54** [comment]
ah ! ok I see .

**Comment by thatblindgeye** [comment]
Definitely appreciate wanting to help improve things, so if you do see things you feel coule be improved (especially on our curriculum repo), please don't hesitate to create an issue (or submit a PR if it's more minor, like verbiage/grammar or anything) :)

Gonna close this and #91 due to the above conversation.

**Pull request closed without merging**
