### PR TITLE
04-animating-underline-on-hover: animation added

### PR DESCRIPTION
**Pull request by Chetan-KK**
# 04-animating-underline-on-hover animation added

## Because
 added new exercise for smooth link hover animation 

## This PR
- This PR includes link underline animation using before after pseudo elements
- This gives smooth transition of underline element on hover

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by codyloyd** [comment]
I'm not sure what value this exercise adds here, and I'm not confident that users are going to be able to solve it without a little more guidance.

**Comment by Chetan-KK** [comment]
i've updated  a readme file so students can understand more clearly how to solve this problem

**Comment by Chetan-KK** [comment]
I've updated readme.md file for more understanding

**Comment by thatblindgeye** [comment]
I agree with the above comment. We currently already have an animation exercise that focuses on transition and transform properties, so I'm not sure if another exercise covering those will be of much value (especially after following 2 other exercises). For now I will be closing this, but please feel free to respond if you have further comments regarding this exercise.

**Pull request closed without merging**
