### PR TITLE
I add a file of FAQ section using html CSS and Java script and i also add some transition to the hover button in the transition folder 

### PR DESCRIPTION
**Pull request by ErfanAalam**
…t for practice and i also add some colors and add transition of scale in hover button folder.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by ErfanAalam** [comment]
i try my best to add some special factors to the project and modify the hover button and make a new folder that consist a FAQ system using HTML, CSS and javascript

**Comment by ManonLef** [comment]
Could you please fill out the entire PR template?

You have ticked the boxes for the requirements, but haven't actually followed them.
Screenshot 2023-10-01 at 20 26 09

**Comment by ErfanAalam** [comment]
> Could you please fill out the entire PR template?
> 
> You have ticked the boxes for the requirements, but haven't actually followed them. Screenshot 2023-10-01 at 20 26 09

i am new in this so please can you tell me what i have to do in details.....

**Comment by ManonLef** [comment]
It looks like you are attempting to PR your personal practice to the original repository. We don't accept personal solutions so I will close this.

**Pull request closed without merging**
