### PR TITLE
TheOdinProject/css-exercises/foundations: add indent to the <body> and <head> tags within <html> for readability

### PR DESCRIPTION
**Pull request by ZebraMilk**
- [x] I have thoroughly read and understand the [CSS Exercises Contributing Guide](https://github.com/TheOdinProject/css-exercises/blob/main/CONTRIBUTING.md)
- [x] The title of this PR is in `file/exercise/folder: brief description of changes` format e.g. `01 flex center: add hint for XYZ`

- [ ] If one exists, I have linked a related open issue to this PR in Step 2 below
- [ ] If changes were requested, I have made them and re-requested a review from the maintainer (top of the right sidebar)

**1. Description of the Changes**
 
Adjust the <body> and <head> indent inside the index.html files and solution.html files in the exercises.

**2. Related Issue**

Closes #XXXXX

### CODE REVIEW

**Comment by thatblindgeye** [comment]
Took a look at a couple of files you updated before realizing how many you updated! Thank you for fixing the indents on all of those, and for the first time contribution! It may take a bit to go through. 

Also thank you for making me realize I should change the verbiage of the second checkbox 😆; the intention was `file OR exercise OR folder` rather than what you did here (don't worry, your title is fine, though!).

**Comment by ZebraMilk** [comment]
Hey, it was a lot of fun learning how to do that quickly. I'm happy to
contribute when I can, I've been doing TOP for 3 days, officially. I look
forward to the coming months!

Yeah, the Pull Request form is a bit confusing, at least for me who takes
clear instruction well haha.

I think it might be useful to indicate which parts of the template you wish
to remain, even if they're not applicable in the specific request. Like, do
I just leave the "Closes XXXXX"?

I learned a lot! Thanks for responding to the request!

Cheers,
ZebraMilk

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Apologies for the delay in reviewing, i've been busy and there were a lot of files to go through here. It looks like there are some merge conflicts that need to be updated; I know some files recently got tweaked a bit so that could be causing the issue. Can you resolve those merge conflicts and re-request a review once everything looks good?

**Comment by thatblindgeye** [comment]
Hi, @ZebraMilk , just wondering if there is an update on the above request?

**Comment by ZebraMilk** [comment]
Apologies! I just got the notification about this. I will look into it later tonight, it will be fun to learn how to resolve conflicts like this, seems like a common thing that would happen in a production environment. Cheers!

**Comment by thatblindgeye** [comment]
No worries, I can't reprimand you after how long it took me to get back to you 😆 These should be relatively simple merge conflcits to resolve, but if you have any questions/are unsure about anything, just let me know.

**Comment by ZebraMilk** [comment]
I have done most of the steps needed to fix this conflict, but I ran into some trouble. I posted about it in the #git-help channel on the discord, if you'd like I can re-post my question here.

Please advise :)

**Comment by thatblindgeye** [comment]
Not entirely sure whether following the instructions mentioned in this PR by GitHub (there should be a "command line instructions" button below the "This branch has conflicts..." message), but otherwise just making a completely new PR and doing the changes again may be easier.

In the future, though, in addition to being sure you don't delete your fork/branch, keep in mind that once you make a PR from a branch on your fork, any additional changes you make and push on that branch will reflect on the PR as well (this came up for another user so figured I would mention it in case).

**Comment by ZebraMilk** [comment]
I do not have any CLI instructions underneath the 
```md
## This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
```
I was able to use the `gh pr checkout 125` from the `<> code` button at the top of the PR to get it onto my machine, but I can't push it anywhere because the fork/repo doesn't exist anymore. I do know now not to wantonly delete repositories haha. This has been a delightful hassle for something so non-critical, as you say, though I am wildly more comfortable working in git/github now than I was when I made this PR. 

I think I will wait a day for GitHub to do their thing, and if no response, I will just make a new fork/new PR and we can let this one go.

Thank you for your patience! I promise future PRs from me will be smoother. Cheers!

**Comment by thatblindgeye** [comment]
Gotcha, it may be only available to maintainers then.

No worries, though. It's better to run into this sort of issue and gain that learning experience for an issue and repo like this! Just leave a comment in here once you get a response from GitHub and let us know what steps you'd like to take from there 🙂

**Comment by ZebraMilk** [comment]
GitHub was delightfully helpful. Done!

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
