### PR TITLE
This Commit fixes #170 opened issue

### LINKED ISSUE #170: 03-grid-layout-3: remove empty declaration blocks
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently both the `style.css` and the pre-solution portion of the `solution.css` files for this exercise include empty declaration blocks, e.g:

```css
.logo {
}
```

These empty declaration blocks are not used in other exercises in this repo and should be removed for consistency, and to avoid leading users towards a specific way of doing things (since this repo emphasizes that there are multiple ways of doing things).

**2. Acceptance Criteria:**

- [ ] Remove empty declaration blocks in the `style.css` and `solution.css` files

**3. Additional Information:**

### PR DESCRIPTION
**Pull request by acb123web**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have ensured that the TOP solution files match the Desired Outcome image

<hr>

**1. Because:**
This PR closes an open issue. Closes #170. 
 https://github.com/TheOdinProject/css-exercises/issues/170

**3. Additional Information:**

### CODE REVIEW

**Comment by acb123web** [comment]
> As Requested i Have done separate PR For this issue

**Comment by thatblindgeye** [comment]
@acb123web Just so you know, there is currently a convo regarding this PR in the original issue. It hasn't been forgotten about.

**Comment by acb123web** [comment]
Yes, Thank you.

**Review by thatblindgeye — APPROVED** [review]

**Review by dm-murphy — APPROVED** [review]
Thanks @thatblindgeye, looks good to me as well! I merged the other PR so this one is good to go as well :-)

**Pull request merged**
