### PR TITLE
Performed Every praticesand completed the responsive website by addin…

### PR DESCRIPTION
**Pull request by ankit071105**
# Performed every responsive work

https://github.com/TheOdinProject/css-exercises/assets/139707943/36d3e720-61d1-47b4-b0cf-6f2e0e24e494

https://github.com/TheOdinProject/css-exercises/assets/139707943/b58f1c96-a131-469f-afd4-b5bd9ef47c17

Screenshot 2023-10-01 at 10 47 55 AM

Screenshot 2023-10-01 at 10 30 43 AM
-exercises/assets/139707943/06fd7e21-fda4-4c20-be58-31a9e517820a)
Screenshot 2023-10-01 at 10 18 33 AM
Screenshot 2023-10-01 at 10 15 20 AM
Screenshot 2023-10-01 at 10 14 25 AM
Screenshot 2023-10-01 at 10 10 01 AM
Screenshot 2023-10-01 at 10 06 01 AM
Screenshot 2023-10-01 at 10 03 35 AM

### CODE REVIEW

**Comment by ManonLef** [comment]
Looking good! However, we don't accept personal solutions to this repository so I'll be closing this

**Comment by ankit071105** [comment]
so how will contribute in this @ManonLef

**Comment by ManonLef** [comment]
What would you like to do @ankit071105 ?
In which way do you want to contribute?

I might be misunderstanding, but it seems you are asking for your personal solutions to be submitted/merged to the exercise files. You can commit solutions to your own fork/clone of this repository so you can look at them later. But we will not merge them since that would change the original files for everyone.

**Comment by ankit071105** [comment]
ok fine

**Pull request closed without merging**
