### PR TITLE
z-index property in css

### PR DESCRIPTION
**Pull request by Ayesha19297**
- Added z-index property of css.

### CODE REVIEW

**Comment by MaoShizhong** [comment]
Closed as this wasn't previously discussed and approved for work.

**Comment by Ayesha19297** [comment]
Should I have to open an issue for this and wait until it gets assigned to
me?

--
Thanks & Regards,
Ayesha
Rising software developer
Email : ***@***.***
Contact no. : +91 8971576186

**Comment by MaoShizhong** [comment]
This repo is for The Odin Project's curriculum. We won't be accepting random PRs for things that need discussion and approval first. The things added in this PR wouldn't be stuff we're planning on adding to this repo anyway.

**Comment by Ayesha19297** [comment]
Ok.
--
Thanks & Regards,
Ayesha
Rising software developer
Email : ***@***.***
Contact no. : +91 8971576186

**Pull request closed without merging**
