### PR TITLE
Preloader Concept Added in Animation

### PR DESCRIPTION
**Pull request by acb123web**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have ensured that the TOP solution files match the Desired Outcome image

<hr>

**1. Because:**

 solution has small piece of code. it will be easy to implement.

**2. This PR:**
Updated New Topic in Animation Folder "Preloader"

**3. Additional Information:**

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Just wanted to check, was there any conversation on our Discord server regarding this additional exercise?

Either way, the PR template should really be filled out as instructed, including the reason for this PR (including what benefits you feel adding this exercise would have).

**Comment by acb123web** [comment]
> i have not joined your discord  server,

>I have explored some projects  and found this repository, in that time i thought that i may contribute some code to this Repositiory. That's why i Raised PR.

**Comment by acb123web** [comment]
> Added Another commit For One Opened issue. ( Issue : https://github.com/TheOdinProject/css-exercises/issues/170)

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
So overall I think having an exercise on keyframes would be a good addition. That said, I think what's been proposed can use some work. I can leave more specific feedback at another point, but namely the format of the files should be following our other exercises. For example, the solution CSS file should include the original CSS, and a commented out section label declaring the start of the solution portion of the file. Additionally, the `style.css` file looks to be including rules that should be left up to the user to add (e.g. the `animation` property).

From there, the README should include some mentions of the timings of each square, e.g. "The first square should animate immediately, with each following square animating 1 second after the previous square", or something along those lines.

I would go through some of our other exercises to get a feel for how they're written, but otherwise I'll be able to leave some more specific feedback at some point (in the middle of getting ready for a move in the coming week so may not be an immediate response).

Additionally, the updates made to the grid files really shouldn't be included in this PR as they are two completely separate issues. If you'd like you can submit a separate PR for those grid updates, but those files need to be removed from this PR.

**Pull request closed without merging**
