### PR TITLE
added landing page

### PR DESCRIPTION
**Pull request by bilalshaikh292**
Added index.html and style.css and linked all the exerscices with it

### CODE REVIEW

**Comment by bilalshaikh292** [comment]
Have solved issue #387

**Comment by ManonLef** [comment]
I will close this because we don't accept personal solution PR's to this repository.

**Comment by ManonLef** [comment]
This will be on hold until the purpose is made more clear. [Request for extra information can be found here](https://github.com/TheOdinProject/css-exercises/issues/387#issuecomment-1744530215)

**Comment by ManonLef** [comment]
Closed with reason stated here: https://github.com/TheOdinProject/css-exercises/issues/387

**Pull request closed without merging**
