### PR TITLE
02-flex-header: Match the solution font with the desired image

### LINKED ISSUE #458: Bug - Flex exercises-02-flex-header: The font in the desired image doesn't match the solution font.
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- The font in the solution.html doesn't match the font in the image of desired output.
- This should be the img of desired output
   
image

**2. How To Reproduce:**
- Open the solution.html in the browser

**3. Expected Behavior:**
- Match font with the solution or update the desired image.

**4. Desktop/Device:**

-   Device: Macbook M1
-   OS: macOS - Sonoma 14.2.1
-   Browser: chrome
-   Version: 120.0.6099.199

**5. Additional Information:**

- I was trying to match the font as well, which I feel would help for future TOP learners if asked not to be bothered with the font (at least in this exercise).

### PR DESCRIPTION
**Pull request by kesava-karri**
## Because

- The font in the desired image varies when compared with the solution's font.

## This PR

- Added the specific font in the `solution.html`

## Issue

Closes #458 

## Additional Information

- Note: The `import` statement needs to be at the top of `css` file, so it couldn't be placed after `/* SOLUTION */` comment

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Review by thatblindgeye — COMMENTED** [review]
Thanks for opening this PR, however this issue seems out of scope for what the exercise is asking. There are times where the included desired outcome image in exercise README's may differ slightly to what a user sees (this could be due to a user's own default settings, for example).

In this case the font potentially being different shouldn't affect a user's solution to the exercise, and including an import statement is out of scope of flex-related learning in the context of this exercise.

Let me know if you have any concerns with the above

**Comment by kesava-karri** [comment]
Yes, I agree. Let's please add a note to not worry about font or adding them to the solution, as few, including me, were trying to match the font as well. 
Thanks for addressing the scope of the exercise. I appreciate your understanding, and I can go ahead and close the PR.

**Comment by thatblindgeye** [comment]
@kesava-karri would you want to update the contents of this PR to make that change instead?

**Comment by kesava-karri** [comment]
@thatblindgeye , I'm happy to make the necessary changes to the PR.

Here are the options for what we can do:

1. Revise the desired image.
2. Include the import statement and font at the beginning of the exercise.
3. Add a note in the markdown stating that it's acceptable not to match the font.

Let me know your preference, and I'll proceed accordingly.

**Comment by thatblindgeye** [comment]
I think just doing option 3 will suffice. While revising the outcome image + adding an import statement in the CSS wouldn't hurt, if we'll be noting that matching the font(s) in the image isn't required we don't necessarily need to make further updates.

**Comment by kesava-karri** [comment]
"Absolutely, I've made the required changes. 

Please disregard the force update; I have mistakenly used `merge` instead of `rebase` while getting the updates from main branch.

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
