### PR TITLE
03-flex-header-2 : Update solution

### PR DESCRIPTION
**Pull request by Aranv-viswas**
Otherwise it gets squeezed if we resize the window, shrinking the profile image (circle) into an oval. So, setting flex-shrink to '0' resolves it

## Because

It  adds more visually appealing responsiveness to the header section. It would be an ideal solution for the beginners as they would know the purpose of flex-shrink property

## This PR

* Added "flex-shrink : 0;" in the "profile-image" item 

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

### CODE REVIEW

**Comment by ephraaaaa** [comment]
Thank you brother! This is insightful for me as a beginner learning in this field.

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Thanks for making this update! This could be a nice little addition to help users understand the flex-[shrink/grow/basis] properties a little more. We'd need to make some updates, though.

- The `flex-shrink: 0;` you inserted should be placed after the `/* SOLUTION */` comment, inside another `.profile-image` block. Where it's at now makes it look like it was part of the original CSS file when it isn't.
- We should add an item to the exercise's README stating that the profile image should not shrink as the window is resized

**Comment by thatblindgeye** [comment]
@Aranv-viswas checking the status of this pr

**Comment by thatblindgeye** [comment]
Gonna close this for now as it isn't a necessary update and a lack of activity. We can reopen this to get it in if the above updates are made.

**Pull request closed without merging**
