### PR TITLE
column number fix in self check

### PR DESCRIPTION
**Pull request by deep7raja**
- [ x] I have thoroughly read and understand the [CSS Exercises Contributing Guide](https://github.com/TheOdinProject/css-exercises/blob/main/CONTRIBUTING.md)
- [x] The title of this PR is in `file/exercise/folder: brief description of changes` format e.g. `01 flex center: add hint for XYZ`

- [x ] If one exists, I have linked a related open issue to this PR in Step 2 below
- [x ] If changes were requested, I have made them and re-requested a review from the maintainer (top of the right sidebar)

**1. Description of the Changes**
 

**2. Related Issue**

Closes #XXXXX

### CODE REVIEW

**Review by thatblindgeye — CHANGES_REQUESTED** [review]
Thank you for the first time contribution! Please re-read the initial post and make sure your complete the checkboxes properly (replace the white space in the brackets with an x, e.g. `[x]`) and make sure you include all the information asked for by the template (namely, a description of what you're changing and why).

**Comment by thatblindgeye** [comment]
Additionally @deep7raja , in the future please check if an issue exists for a change you are proposing (in this case one does, #120 ), and if it does please comment on the issue and wait to be assigned before doing any work. You should also link the issue I mentioned in your original post.

**Comment by deep7raja** [comment]
Since the PR already exists, I am closing this PR. Thanks you your reply.

**Comment by thatblindgeye** [comment]
To be clear, there was no PR for this, but rather an issue (think of a PR as "here are the changes I made" and an issue as "Here is a report of a problem I noticed"). I was simply mentioning that in the future you check if an issue exists and ask to be assigned before doing any work, and also link any open issue in the PR if one exists. I do appreciate you wanting to improve things and contribute and I hope you'll contribute again in the future! 🙂

**Pull request closed without merging**
